<a href="https://colab.research.google.com/github/THANUSH0000/python-machine-earning/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("original array:\n",arr)

original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [ ]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("original array:\n",arr)

original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [ ]:
#return every other rows
print("\n Every other rows:\n",arr[0:3:2])


 Every other rows:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [ ]:
#return every other element from the entire array
arr=np.array([1,2,3,4,5,6,7])
print("\n original array:",arr)
print("\n Returns every other elements in the array : arr[::2] :",arr[::2])


 original array: [1 2 3 4 5 6 7]

 Returns every other elements in the array : arr[::2] : [1 3 5 7]


In [ ]:
#slicing array
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
temp=arr[:2,:3]
print("\n Array with first 2 rows and 3 columns :\n", temp)


 Array with first 2 rows and 3 columns :
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [ ]:
#integer array indxing
apple=arr[[0,1,2,3],[3,2,1,0]]
print("\n Element at indices (0,3),(1,2),(2,1),"",(3,0).\n",apple)


 Element at indices (0,3),(1,2),(2,1),,(3,0).
 [4. 6. 0. 3.]


In [ ]:
#Boolean array indexing
cond=arr>2
#cond is a boolean array
temp=arr[cond]
print("\n Element greater than 2.\n",temp)


 Element greater than 2.
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [ ]:
#joining two arrays
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#horizontal join
arr3=np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [ ]:
#vertical join
arr4=np.vstack((arr1,arr2))
print(arr4)

[[1 2 3]
 [4 5 6]]


In [ ]:
#depth join
arr5=np.dstack ((arr1,arr2))
print(arr5)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
#splitting of array
arr=np.array([1,2,3,4,5,6])
arr6=np.array_split(arr,3)
print(arr)
print(arr6[0])
print(arr6[1])
print(arr6[2])

[1 2 3 4 5 6]
[1 2]
[3 4]
[5 6]
